[tools]
node = "lts"
python = "miniconda3-latest"
deno = "latest"
# pnpm = "latest"
java = "temurin-25"
ruby = "latest"
go = "latest"
bun = "latest"
erlang = "latest"
zig = "latest"
uv = "latest"
fnox = "latest"
herdr = "latest"
pnpm = "latest"
