set shell=/bin/bash
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
"Plugin 'tpope/vim-fugitive'
" plugin from http://vim-scripts.org/vim/scripts.html
"Plugin 'L9'
" Git plugin not hosted on GitHub
"Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
"Plugin 'file:///home/gmarik/path/to/plugin'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
"Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Avoid a name conflict with L9
"Plugin 'user/L9', {'name': 'newL9'}

"" appearance
Plugin 'altercation/vim-colors-solarized'
Plugin 'tomasr/molokai'

"" git
Plugin 'tpope/vim-fugitive'
Plugin 'airblade/vim-gitgutter'

"" languages
Plugin 'scrooloose/syntastic'
Plugin 'majutsushi/tagbar'
Plugin 'plasticboy/vim-markdown'
Plugin 'pangloss/vim-javascript'
Plugin 'fatih/vim-go'
Plugin 'toyamarinyon/vim-swift'
Plugin 'ekalinin/Dockerfile.vim'

"" editing
Plugin 'godlygeek/tabular'
Plugin 'tpope/vim-surround'
Plugin 'Shougo/neocomplcache.vim'
Plugin 'Shougo/neosnippet'
Plugin 'Shougo/neosnippet-snippets'

"" vim
Plugin 'bling/vim-airline'
Plugin 'edkolev/tmuxline.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'Lokaltog/vim-easymotion'
Plugin 'zhaocai/GoldenView.Vim'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

"" Config
" editor
syntax enable "문법강조를 사용
set imd "모드를 변경하면 자동으로 키보드를 영문 레이아웃으로 변경
set expandtab "탭대신 스페이스
set tabstop=2 "탭 눌렀을때 2칸
set shiftwidth=2 "자동 들여쓰기 사용시 2칸
set softtabstop=2
set number "행표시
set autoindent " 자동으로 들여쓰기를 한다.
set smartindent " 똑똑한 들여쓰기 사용
set background=dark "바탕 어두움 설정

"" appearance
"http://stackoverflow.com/questions/7278267/incorrect-colors-with-vim-in-iterm2-using-solarized
let g:solarized_termtrans = 1
let g:solarized_visibility = "high"
let g:solarized_contrast = "high"
"https://github.com/tomasr/molokai
let g:molokai_original = 1
let g:rehash256 = 1
colorscheme molokai
" colorscheme solarized

" vim-airline
set guifont=Source\ Code\ Pro\ for\ Powerline
set laststatus=2
set t_Co=256 "http:://unix.stackexchange.com/questions/154012/terminal-colors-for-vim-airline-and-tmux-tmuxline 터미널 컬러 설정
let g:airline_powerline_fonts = 1
" Enable the list of buffers
let g:airline#extensions#tabline#enabled = 1
" Show just the filename
let g:airline#extensions#tabline#fnamemod = ':t'
"let g:airline_theme='molokai'
let g:airline_theme='solarized'

" vim-markdown
" https://github.com/airblade/vim-gitgutter/issues/164
let g:vim_markdown_folding_disabled=1
highlight clear SignColumn
highlight GitGutterAdd ctermfg=green guifg=darkgreen
highlight GitGutterChange ctermfg=yellow guifg=darkyellow
highlight GitGutterDelete ctermfg=red guifg=darkred
highlight GitGutterChangeDelete ctermfg=yellow guifg=darkyellow

