set shell=/bin/bash

if has('nvim')
  call plug#begin('~/.local/share/nvim/plugged')
else
  call plug#begin('~/.vim/plugged')
endif

"" appearance
Plug 'rakr/vim-one'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'ryanoasis/vim-devicons'
Plug 'nathanaelkane/vim-indent-guides'
Plug 'junegunn/vim-emoji'

"" git
Plug 'tpope/vim-git'
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'

"" editing
Plug 'liuchengxu/vim-better-default'
Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }
Plug 'junegunn/vim-easy-align'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
Plug 'majutsushi/tagbar'
Plug 'editorconfig/editorconfig-vim'
Plug 'w0rp/ale'
Plug 'metakirby5/codi.vim'
" Plug 'sbdchd/neoformat'

"" complete, snippet
Plug 'roxma/nvim-completion-manager'
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
Plug 'othree/csscomplete.vim'
Plug 'roxma/nvim-cm-tern',  {'do': 'npm install'}

"" vim
Plug '/usr/local/opt/fzf' | Plug 'junegunn/fzf.vim'
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
Plug 'Xuyuanp/nerdtree-git-plugin'

"" languages, syntax
Plug 'sheerun/vim-polyglot'
Plug 'idris-hackers/idris-vim'
Plug 'tfnico/vim-gradle'
Plug 'niftylettuce/vim-jinja'
Plug 'reasonml-editor/vim-reason-plus'

call plug#end()


"""""""""
"" Config


"""""""""
"" editor
let mapleader=" "
let maplocalleader=","
set mouse=a

nmap <Leader>q :nohlsearch<CR> " 검색 하이라이팅 키고 끄기
nmap <Leader>o :set paste!<CR> " 코드블럭 붙여넣기 모드를 키고 끄기
" nmap <C-n> :bnext<CR> " 다음 순서 버퍼 이동
" nmap <C-p> :bprev<CR> " 이전 순서 버퍼 이동
" nmap <C-e> :e#<CR> " 방금전 버퍼로 이동


"""""""""""""
"" appearance
" set t_Co=256 " http:://unix.stackexchange.com/questions/154012/terminal-colors-for-vim-airline-and-tmux-tmuxline 터미널 컬러 설정
set termguicolors " nvim ture color 지원
colorscheme one

" one theme
set background=dark


""""""""""""""""""""
"" vim-better-default
let g:vim_better_default_persistent_undo = 1
runtime! plugin/default.vim
set shiftwidth=2
set tabstop=2
set softtabstop=2
set wildmode=full


""""""""""""""""""""
"" vim-vue
let g:vue_disable_pre_processors=1
autocmd FileType vue syntax sync fromstart


""""""""""""""
"" vim-airline
"set guifont=<FONT_NAME>:h<FONT_SIZE>
"set guifont=Source\ Code\ Pro\ for\ Powerline
"set guifont=Meslo\ LG\ M\ Regular\ for\ Powerline\ Nerd\ Font\ Complete
set guifont=MesloLGM\ Nerd\ Font
set laststatus=2
let g:airline_powerline_fonts = 1
" Enable the list of buffers
let g:airline#extensions#tabline#enabled = 1
" Show just the filename
let g:airline#extensions#tabline#fnamemod = ':t'
let g:airline_theme='one'

""""""""""
"" python
let g:python_host_prog = '/Users/dididi/.pyenv/versions/neovim2/bin/python'
let g:python3_host_prog = '/Users/dididi/.pyenv/versions/neovim3/bin/python'

"""""""""""""""
"" vim-markdown
let g:vim_markdown_folding_disabled=1
let g:vim_markdown_frontmatter=1


""""""""""""""""
"" vim-gitgutter
" https://github.com/airblade/vim-gitgutter/issues/164
" highlight clear SignColumn
" highlight GitGutterAdd ctermfg=green guifg=darkgreen
" highlight GitGutterChange ctermfg=yellow guifg=darkyellow
" highlight GitGutterDelete ctermfg=red guifg=darkred
" highlight GitGutterChangeDelete ctermfg=yellow guifg=darkyellow


""""""""""""
"" NERDTree
" map <C-n> :NERDTreeToggle<CR>
map <Leader>e :NERDTreeToggle<CR>
" map <C-w><C-e> :NERDTreeToggle<CR>
" Auto start NERD tree when opening a directory
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | wincmd p | endif

" Auto start NERD tree if no files are specified
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | exe 'NERDTree' | endif

" Let quit work as expected if after entering :q the only window left open is NERD Tree itself
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif


"""""""""""""""""""
"" EditorConfig-vim
let g:EditorConfig_core_mode = 'external_command'


"""""""""""""""
"" fugitive.vim
autocmd QuickFixCmdPost *grep* cwindow


"""""""""
"" tagbar
nmap <F8> :TagbarToggle<CR>


"""""""""""""
"" vim-easy-align
" Start interactive EasyAlign in visual mode (e.g. vipga)
xmap ga <Plug>(EasyAlign)

" Start interactive EasyAlign for a motion/text object (e.g. gaip)
nmap ga <Plug>(EasyAlign)<Paste>


""""""
"" fzf
set rtp+=/usr/local/opt/fzf

" This is the default extra key bindings
let g:fzf_action = {
  \ 'ctrl-t': 'tab split',
  \ 'ctrl-x': 'split',
  \ 'ctrl-v': 'vsplit' }

" Enable per-command history.
" CTRL-N and CTRL-P will be automatically bound to next-history and
" previous-history instead of down and up. If you don't like the change,
" explicitly bind the keys to down and up in your $FZF_DEFAULT_OPTS.
let g:fzf_history_dir = '~/.local/share/fzf-history'

" Mapping selecting mappings
nmap <leader><tab> <plug>(fzf-maps-n)
xmap <leader><tab> <plug>(fzf-maps-x)
omap <leader><tab> <plug>(fzf-maps-o)

" fzf statusline
function! s:fzf_statusline()
  " Override statusline as you like
  highlight fzf1 ctermfg=161 ctermbg=251
  highlight fzf2 ctermfg=23 ctermbg=251
  highlight fzf3 ctermfg=237 ctermbg=251
  setlocal statusline=%#fzf1#\ >\ %#fzf2#fz%#fzf3#f
endfunction

autocmd! User FzfStatusLine call <SID>fzf_statusline()

nnoremap <silent> <Leader>t :Tags<CR>
nnoremap <silent> <leader>f :Files<CR>
nnoremap <silent> <leader>b :Buffers<CR>
nnoremap <silent> <leader>w :Windows<CR>
nnoremap <silent> <leader>l :BLines<CR>
nnoremap <silent> <leader>? :History<CR>
nnoremap <silent> <leader>/ :execute 'Ag ' . input('Ag/')<CR>
nnoremap <silent> <leader>. :AgIn<space>

"""""""""
"" vim-emoji
set completefunc=emoji#complete


"""""""""
"" ultisnips

" Trigger configuration. Do not use <tab> if you use https://github.com/Valloric/YouCompleteMe.
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"

" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit="vertical"


"""""""""
"" LanguageClient-neovim

let g:LanguageClient_serverCommands = {
    \ 'rust': ['rustup', 'run', 'nightly', 'rls'],
    \ 'javascript': ['javascript-typescript-stdio'],
    \ 'javascript.jsx': ['javascript-typescript-stdio'],
    \ 'reason': ['ocaml-language-server', '--stdio'],
    \ 'ocaml': ['ocaml-language-server', '--stdio'],
    \ }

nnoremap <silent> K :call LanguageClient_textDocument_hover()<CR>
nnoremap <silent> gd :call LanguageClient_textDocument_definition()<CR>
nnoremap <silent> <F2> :call LanguageClient_textDocument_rename()<CR>


""""""""""'
"" ale

" Enable completion where available.
let g:ale_completion_enabled = 1
" Set this. Airline will handle the rest.
let g:airline#extensions#ale#enabled = 1
